name: api
description: The interface and models for an API providing access to todos
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.8.0
  uuid: ^3.0.7
