name: local_storage_api
description: A flutter implementation of the Api that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  api:
    path: "../api"
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
